# Generated by Django 4.1.6 on 2023-04-09 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleadvisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduleadvisor.advisor'),
        ),
    ]
