# Generated by Django 4.1.6 on 2023-04-13 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleadvisor', '0003_schedule_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif', models.CharField(default='', max_length=400)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduleadvisor.schedule')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduleadvisor.student')),
            ],
        ),
    ]
