# Generated by Django 4.1.6 on 2023-04-13 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleadvisor', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Time published'),
        ),
    ]
