# Generated by Django 4.1.6 on 2023-04-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleadvisor', '0005_notification_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
