# Generated by Django 4.1.6 on 2023-04-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleadvisor', '0006_advisor_email_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='schedule_filter',
            field=models.CharField(default='all', max_length=100),
        ),
    ]
