# Generated by Django 4.1.6 on 2023-04-30 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleadvisor', '0008_alter_student_schedule_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduleadvisor.advisor'),
        ),
    ]
