# Generated by Django 4.1.6 on 2023-05-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleadvisor', '0009_alter_student_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='credits',
            field=models.CharField(default='', max_length=10),
        ),
    ]
