# Generated by Django 4.1.6 on 2023-05-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleadvisor', '0011_alter_schedule_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartcourse',
            name='acad_career_descr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cartcourse',
            name='class_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartcourse',
            name='enrollment_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartcourse',
            name='section_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedulecourse',
            name='acad_career_descr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedulecourse',
            name='class_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedulecourse',
            name='enrollment_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedulecourse',
            name='section_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='searchcourse',
            name='acad_career_descr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='searchcourse',
            name='class_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchcourse',
            name='enrollment_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchcourse',
            name='section_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
